### PR TITLE
Bring in upstream changes into master

### PR DESCRIPTION
**Pull request by rogeruiz**
Pairing with @rememberlenny

⚠️ 🚧 #40 needs to be merged in to this branch before merging this into `master` 🚧 ⚠️

### CODE REVIEW

**Comment by rogeruiz** [comment]
Looks like we gotta fix some tests @rememberlenny. Gonna look into this locally. 😢 🗞

**Comment by rogeruiz** [comment]
Blocked because tests are failing and we'll need to update the submodules in our CF boshrelease as well.

**Comment by rogeruiz** [comment]
👍 tests are ~~mostly~~ passing. Turns out it was a node library causing the error :trollface: 

_It was actually the `{cg->govcloud}` path change not being reflected in the tests_ 👼

**Comment by rogeruiz** [comment]
[One of the LDAP tests failed](https://travis-ci.org/18F/cg-uaa/jobs/209597832#L2044-L2045), but wahtvere. I think we can still safely merge this in the morning. [The rest of them passed](https://travis-ci.org/18F/cg-uaa/builds/209597823).

```
ERROR: failed to upload: /home/travis/build/cloudfoundry/uaa/uaa/build/reports/tests/org.cloudfoundry.identity.uaa.integration.feature.OIDCLoginIT/successfulLoginWithOIDC_and_SAML_Provider.png
  err: The AWS Access Key Id you provided does not exist in our records.
```

**Review by cnelson — APPROVED** [review]

**Pull request merged**
