### PR TITLE
Merge upstream 3.9.3

### PR DESCRIPTION
**Pull request by LinuxBozo**
This will get our UAA up to 3.9.3, and fixes 18F/cg-product#496

/cc @cnelson @rogeruiz

### CODE REVIEW

**Comment by rogeruiz** [comment]
Does the build actually need to take 50 min to complete?

**Comment by LinuxBozo** [comment]
Travis is passing the tests for mysql & postgres, but default and ldap versions are hitting the Travis build time limit. 😞

**Comment by cnelson** [comment]
I think as long as postgres is passing it's fine.  That's what we are
running.

**Review by rogeruiz — APPROVED** [review]
Approving even though the tests take too long on Travis. The local tests are passing.

**Pull request merged**
